Update aria2-builer.yml

diff --git a/.github/workflows/aria2-builer.yml b/.github/workflows/aria2-builer.yml
--- a/.github/workflows/aria2-builer.yml
+++ b/.github/workflows/aria2-builer.yml
@@ -1,12 +1,3 @@
-#
-# Copyright (c) 2020 P3TERX <https://p3terx.com>
-#
-# This is free software, licensed under the GNU General Public License v3.
-# See /LICENSE for more information.
-#
-# https://github.com/P3TERX/Aria2-Pro-Core
-#
-
 name: Aria2 Builder
 
 on:
@@ -40,14 +31,14 @@ jobs:
           BUILD_SCRIPT: aria2-gnu-linux-cross-build-i386.sh
 
     steps:
-
     - name: Install QEMU
-      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+      run: |
+        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
 
-    - name: Checkout
-      uses: actions/checkout@v2
+    - name: Checkout repository
+      uses: actions/checkout@v3  # Updated to latest stable version
 
-    - name: Build
+    - name: Build with Docker
       env:
         DOCKER_BUILDKIT: 1
         BUILDER_IMAGE: ${{ matrix.BUILDER_IMAGE }}
@@ -61,8 +52,8 @@ jobs:
           2>&1 | tee build.log
 
     - name: Output Error Log
-      if: (!cancelled())
-      run: grep -iE 'fatal|error|critical|failure|warning' build.log
+      if: always()  # Changed to `always()` to ensure this step runs even on failure
+      run: grep -iE 'fatal|error|critical|failure|warning' build.log || true
 
     - name: Check Version
       run: |
@@ -71,7 +62,7 @@ jobs:
         ./aria2c -v 2>&1 | tee ./output/version-${{ matrix.PLATFORMS }}.txt
 
     - name: Upload artifact
-      uses: actions/upload-artifact@v2
+      uses: actions/upload-artifact@v3  # Updated to latest stable version
       with:
         name: aria2-${{ matrix.PLATFORMS }}
         path: output
